version: "3.8"
services:

  db:
    image: mysql:8.0.16
    # UTILIZAR EM MAC APPLE SILICON    platform: linux/x86_64
    container_name: challenge_flix_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 5
    networks:
      - challenge_flix_network
    volumes:
      - ./local/db:/var/lib/mysql
      - ./local/init.sql:/data/application/init.sql
    ports:
      - 3306:3306
    command: --init-file /data/application/init.sql

  aws:
    image: localstack/localstack:latest
    container_name: challenge_flix_aws
    environment:
      - DEBUG=1
      - LOCALSTACK_HOSTNAME=localhost
      - TEST_AWS_ACCOUNT_ID=000000000000
      - EDGE_PORT=4566
      - SERVICES=sqs
    networks:
      - challenge_flix_network
    volumes:
    - ./local/aws:/var/lib/localstack
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 4566:4566


networks:
  challenge_flix_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/16
          gateway: 172.23.0.1